[build]
  # Directory to change to before starting a build
  base = "."
  # Directory that contains the deploy-ready HTML files and assets
  publish = "."
  # Default build command
  command = "echo 'Static site - no build needed'"

[build.environment]
  # Set Node.js version (if needed for build tools)
  NODE_VERSION = "18"

[[headers]]
  # Define which paths this specific [[headers]] block will cover
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://api.qrserver.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net; font-src 'self' https://fonts.gstatic.com https://cdn.jsdelivr.net; img-src 'self' data: https: blob:; connect-src 'self' https://www.google-analytics.com; frame-src 'self'"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Cache control for HTML files
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  # Cache control for assets
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Cache control for CSS and JS
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect rules (alternative to _redirects file)
[[redirects]]
  from = "http://saiprudvi.me/*"
  to = "https://saiprudvi.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.saiprudvi.me/*"
  to = "https://saiprudvi.me/:splat"
  status = 301
  force = true